Tidied up the arduino update script

diff --git a/bin/ninja_update_arduino b/bin/ninja_update_arduino
--- a/bin/ninja_update_arduino
+++ b/bin/ninja_update_arduino
@@ -44,10 +44,10 @@ if [ -e arduino.hex ] && [ -n "$remote_checksum" ] && [ "$remote_checksum"="$loc
 		echo "[System] `date` Flashing Arduino...Pass $i Failed!!!"
 	done
 	echo "[System] `date` Critical error! Failed flashing Arduino in 3 passes." >> /var/log/ninjablock.log
-	rm arduino.hex
-	exit 1
 else
-	echo "[System] `date` Invalid Arduino Checksum" >> /var/log/ninjablock.log
-	rm arduino.hex
-	exit 1
+	echo "[System] `date` Could not retrieve valid arduino update binary." >> /var/log/ninjablock.log
 fi
+if [ -e arduino.hex ]; then
+	rm arduino.hex
+fi
+exit 1
