Utilities pulling from S3

diff --git a/bin/ninja_update_utilities b/bin/ninja_update_utilities
--- a/bin/ninja_update_utilities
+++ b/bin/ninja_update_utilities
@@ -3,7 +3,21 @@
 code_dir=/opt/ninja
 util_dir=/opt/utilities
 tmp_dir=$util_dir/tmp
-cd $util_dir
-git pull
-cp -Rf $util_dir/init/* /etc/init/
-chmod ubuntu:ubuntu $util_dir/bin/ninja_update_node
+cd $tmp_dir
+wget -O utilities.tar.gz https://s3.amazonaws.com/ninjablocks/code/beagle/utilities/$NINJA_ENV.tar.gz
+remote_checksum=$(wget https://s3.amazonaws.com/ninjablocks/code/beagle/utilities/$NINJA_ENV.checksum -q -O -)
+local_checksum=$(sha1sum utilities.tar.gz | awk '{ print $1 }')
+if [ "$remote_checksum"="$local_checksum" ]; then
+	echo "[System] Updating Utilities" >> /var/log/ninjablock.log
+	tar -zxf utilities.tar.gz
+	cp -Rf utilities/* $util_dir/
+	cp -Rf $util_dir/init/* /etc/init/
+	chmod ubuntu:ubuntu $util_dir/bin/ninja_update_node
+	rm utilities.tar.gz
+	rm -rf utilities
+	exit 0
+else
+	echo "[System] Invalid Utilities Checksum" >> /var/log/ninjablock.log
+	rm $NINJA_ENV.tar.gz
+	exit 1
+fi
