flash beaglebone and beaglebone black with same script

diff --git a/bin/ninja_update_arduino b/bin/ninja_update_arduino
--- a/bin/ninja_update_arduino
+++ b/bin/ninja_update_arduino
@@ -1,4 +1,43 @@
 #!/bin/bash
+
+script_name=`basename $0`
+
+function printUsage {
+	echo "Usage: "
+	echo "  $script_name"
+	echo "  $script_name <file.hex>"
+	echo "    eg. $script_name arduino.hex"
+	echo "  $script_name -f <version>"
+	echo "    eg. $script_name -f V12"
+}
+
+function exitSuccess {
+        exit 0
+}
+function exitFail {
+        exit 1
+}
+function exitUsage {
+	printUsage
+	exitFail
+}
+
+function setPins {
+    if [[ ${NINJA_CLIENT_NAME} = "beaglebone-black" ]]; then
+    	flashPin=44
+    elif [[ ${NINJA_CLIENT_NAME} = "beagle" || ${NINJA_CLIENT_NAME} = "beagle-armv7l"  ]]; then
+    	flashPin=38
+    	$util_dir/bin/setgpio;
+    	$util_dir/bin/setserial;
+    else
+    	flashPin=38  #default to beagle
+    	$util_dir/bin/setgpio;
+    	$util_dir/bin/setserial;
+    fi
+}
+
+official_update=false
+
 # Define directories
 # Setup the environment
 
@@ -8,7 +47,10 @@ fi
 code_dir=/opt/ninja
 util_dir=/opt/utilities
 tmp_dir=$util_dir/tmp
-uri="http://s3.amazonaws.com/ninjablocks/code/beagle/arduino"
+uri="http://s3.amazonaws.com/ninjablocks/code/${NINJA_CLIENT_NAME:-"beagle"}/arduino"
+
+setPins
+
 # Pull new code from repo
 cd $tmp_dir
 # Robustness hack
@@ -17,65 +59,74 @@ echo '{"DEVICE":[{"G":"0","V":0,"D":999,"DA":"FFFFFF"}]}' > /dev/ttyO1
 
 sleep 2
 
-
-
 function flashArduino {
 
 	if [[ ! -e $1 ]]
 	then
 		echo "$1 does not exist"
-		exit 0
+		exitFail
 	fi
 
 	echo "[System] `date` Arduino Flashing Started" >> /var/log/ninjablock.log
-	$util_dir/bin/setgpio;
-	#sleep 1;
-	$util_dir/bin/setserial;
-	#sleep 1;
-	echo "38" > /sys/class/gpio/export;
-	#sleep 1;
-	echo "out" > /sys/class/gpio/gpio38/direction;
-	#sleep 1;
+	
+	echo "$flashPin" > /sys/class/gpio/export;
+	echo "out" > /sys/class/gpio/gpio$flashPin/direction;
+	
 	for i in 1 2 3 4
 	do
 		echo "[System] `date` Flashing Arduino...Pass $i." >> /var/log/ninjablock.log;
-		sudo echo "1" > /sys/class/gpio/gpio38/value;
+		sudo echo "1" > /sys/class/gpio/gpio$flashPin/value;
 		sleep 1;
-		sudo echo "0" > /sys/class/gpio/gpio38/value;
+		sudo echo "0" > /sys/class/gpio/gpio$flashPin/value;
 		#sleep 1;
 		#sudo echo "1" > /sys/class/gpio/gpio38/value;
 		#sleep 1;
+
 		avrdude -C $util_dir/etc/avrdude.conf  -p atmega328p -c arduino -P /dev/ttyO1 -b 57600 -D -U flash:w:$1:i;
+
 		if [ "$?" = "0" ]; then
-			sudo echo "1" > /sys/class/gpio/gpio38/value;
+			sudo echo "1" > /sys/class/gpio/gpio$flashPin/value;
 			echo "[System] `date` Successfully flashed Arduino in pass $i." >> /var/log/ninjablock.log;
-			# rm arduino.hex
+			touch /etc/opt/ninja/.has_updated_arduino
+			if $official_update ; then
+				rm arduino.hex
+			fi
 			sync
-			exit 0
+			exitSuccess
 		fi
 		echo "[System] `date` Flashing Arduino...Pass $i Failed!"
 	done
 	echo "[System] `date` Critical error! Failed flashing Arduino in 3 passes." >> /var/log/ninjablock.log
 }
 
-
-
-
-if [[ $# -eq 1 ]] #flash with filename given in params
-then
-	flashArduino $1
-else              #update normally
-
-	# fetch the model
-	arduino_mv=$(/opt/utilities/bin/fetch_arduino_version)
-
-	# exit if there is an error
-	if [ "$?" != "0" ]
-	then
-		echo "[System] `date` Arduino Update Failed. Could not retrieve version number." >> /var/log/ninjablock.log
-		exit 0;
+if [[ $# -eq 1 ]]
+then  
+	if [[ $1 == -* ]] || [[ $1 == \? ]]; then
+		exitUsage
+	else #flash with filename given in params
+		flashArduino $1
 	fi
+else 
+	if [[ $# -ge 2 ]]
+	then
+		if [[ $1 != "-f" ]]
+		then
+			exitUsage
+		else
+			arduino_mv="$2_(unknown)" # force flash of unknown firmward version on specified board
+		fi
+	else
+		# attempt to fetch the model
+		arduino_mv=$(/opt/utilities/bin/fetch_arduino_version)
 
+		if [ "$?" != "0" ]
+		then
+			echo "[System] `date` Arduino Update Failed. Could not retrieve version number." >> /var/log/ninjablock.log
+			echo "Arduino Update Failed. Could not retrieve version number."
+			echo "(Can force with:  $script_name -f V12 )"
+			exitFail
+		fi
+	fi
 	if [ -n "$arduino_mv" ] && [[ "$arduino_mv" == *_* ]] # if the response is not null, and is in the form model_version
 	then
 		# split the string by "_"
@@ -107,9 +158,9 @@ else              #update normally
 	code=$(curl -s -o /dev/null -I -w "%{http_code}" $url)
 	if [ "$code" != "200" ]
 	then
-		echo "[System] `date` Arduino Update Failed. Could not fetch binary" >> /var/log/ninjablock.log
-		echo "url is $url"
-		exit 0;
+		echo "[System] `date` Arduino Update Failed. Could not fetch binary ($url)" >> /var/log/ninjablock.log
+		echo "Arduino Update Failed. Could not fetch binary ($url)"
+		exitFail
 	fi
 	curl --output arduino.hex $url
 	# Fetch the remote checksum
@@ -117,15 +168,14 @@ else              #update normally
 	# Calculate the local checksum
 	local_checksum=$(sha1sum arduino.hex | awk '{ print $1 }')
 	# If we have a file, have fetched the remote checksum, and it is the same as the local checksum
-	if [ -e arduino.hex ] && [ -n "$remote_checksum" ] && [ "$remote_checksum" = "$local_checksum" ] 
+	if [ -e arduino.hex ] && [ -n "$remote_checksum" ] && [ "$remote_checksum" = "$local_checksum" ]
 	then
-		touch /etc/opt/ninja/.has_updated_arduino
+		official_update=true
 		flashArduino arduino.hex
-		rm arduino.hex
 	else
 		echo "[System] `date` Could not retrieve valid arduino update binary." >> /var/log/ninjablock.log
 	fi
-	
+
 	sync
-	exit 0
 fi
+exitFail
